-- CRIANDO A TABELA EMPRESA
CREATE TABLE EMPRESA (
 COD_EMPRESA INT NOT NULL PRIMARY KEY,
 NOME_EMPRESA VARCHAR2(50),
 FANTASIA VARCHAR2(15)
 );
 
 --CRIANDO SEQUENCIA PARA O CODIGO EMPRESA
 
 CREATE SEQUENCE SEQ_EMP START WITH 1 INCREMENT BY 1 NOMAXVALUE;

-- CADASTRO DE UNIDADE FEDERAL, UTLIZADO POR TODAS EMPRESAS
--DROP TABLE UF;
CREATE TABLE UF
(
	COD_UF VARCHAR2(2) NOT NULL PRIMARY KEY,
    SIGLA_UF VARCHAR2(2) NOT NULL,
	NOME_UF VARCHAR2(30) NOT NULL
);

 
--TABELAS CIDADES
-- CADASTRO DE CIDADES, UTLIZADO POR TODAS EMPRESAS
--DROP TABLE CIDADES;
CREATE TABLE CIDADES
	(
	COD_CIDADE VARCHAR2(7) NOT NULL PRIMARY KEY,
	COD_UF VARCHAR2(2) NOT NULL,
	NOME_CIDADE VARCHAR2(50) NOT NULL,
	CONSTRAINT FK_CID1 FOREIGN KEY (COD_UF) REFERENCES UF(COD_UF)
	);

--CRIANDO TABELAS CLIENTES
CREATE TABLE CLIENTES
	(
    COD_EMPRESA INT NOT NULL,
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
	RAZAO_CLIENTE VARCHAR2(100)NOT NULL,
	FANTASIA VARCHAR2(15) NOT NULL,
	ENDERECO VARCHAR2(50) NOT NULL,
	NRO VARCHAR2(10) NOT NULL,
	BAIRRO VARCHAR2(20) NOT NULL,
	COD_CIDADE VARCHAR2(7) NOT NULL,
	CEP VARCHAR2(8),
	CNPJ_CPF VARCHAR2(15),
	TIPO_CLIENTE CHAR(1) CONSTRAINT CK_TC1 CHECK (TIPO_CLIENTE in ('F', 'J')),
	DATA_CADASTRO DATE NOT NULL,
	COD_PAGTO INT ,
    CONSTRAINT FK_COD_EMP1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
	CONSTRAINT FK_CLI1 FOREIGN KEY (COD_CIDADE) REFERENCES CIDADES(COD_CIDADE)
	);

 -- CRIANDO SEQUENCIA PARA CLIENTES;  
 CREATE SEQUENCE SEQ_CLI START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CRIACAO TABELA FORNECEDORES
CREATE TABLE FORNECEDORES
(   COD_EMPRESA INT NOT NULL,
    ID_FOR INT  NOT NULL PRIMARY KEY,
	RAZAO_FORNEC VARCHAR2(100)NOT NULL,
	FANTASIA VARCHAR2(15) NOT NULL,
	ENDERECO VARCHAR2(50) NOT NULL,
	NRO VARCHAR2(10) NOT NULL,
	BAIRRO VARCHAR2(20) NOT NULL,
	COD_CIDADE VARCHAR2(7) NOT NULL,
	CEP VARCHAR2(8),
	CNPJ_CPF VARCHAR2(15),
	TIPO_FORNEC CHAR(1) CONSTRAINT CK_TF1 CHECK (TIPO_FORNEC in ('F', 'J')),
	DATA_CADASTRO DATE NOT NULL,
	COD_PAGTO INT ,
    CONSTRAINT FK_COD_EMP2 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
	CONSTRAINT FK_FOR1 FOREIGN KEY (COD_CIDADE) REFERENCES CIDADES(COD_CIDADE)
	);
    
 -- CRIANDO SEQUENCIA PARA FORNECEDORES;  
 CREATE SEQUENCE SEQ_FOR START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--TABELAS TIPO DE MATERIAL
CREATE TABLE TIPO_MAT
	(
	COD_TIP_MAT INT  NOT NULL PRIMARY KEY,
	DESC_TIP_MAT VARCHAR2(20) NOT NULL
	);
    
--CRIANDO SEQUENCIA TIPO MATERIAL
 CREATE SEQUENCE SEQ_TIP_MAT START WITH 1 INCREMENT BY 1 NOMAXVALUE;
 
--CRIANDO TABELAS MATERIAL
CREATE TABLE MATERIAL
	(
    COD_EMPRESA INT NOT NULL,
	COD_MAT INT NOT NULL,
	DESCRICAO VARCHAR2(50) NOT NULL,
	PRECO_UNIT DECIMAL(10,2) NOT NULL,
	COD_TIP_MAT INT NOT NULL,
    CONSTRAINT FK_COD_EMP3 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
	CONSTRAINT FK_MAT1 FOREIGN KEY (COD_TIP_MAT) REFERENCES TIPO_MAT(COD_TIP_MAT),
    CONSTRAINT PK_EMP_MAT PRIMARY KEY (COD_EMPRESA,COD_MAT)
	);


    
CREATE TABLE MAT_FORNEC
(
    COD_EMPRESA INT NOT NULL,
    COD_MAT INT NOT NULL,
    ID_FOR INT NOT NULL,
    CONSTRAINT PK_MAT_FOR PRIMARY KEY (COD_EMPRESA,COD_MAT,ID_FOR),
    CONSTRAINT FK_MAT_FOR1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT FK_MAR_FOR2 FOREIGN KEY (ID_FOR) REFERENCES FORNECEDORES(ID_FOR)
    );

--CRIANDO INDEX
--SIMULA ERRO INDEX DE CHAVE PRIMARIA
--CREATE INDEX IX_MAT1 ON MATERIAL(COD_EMPRESA,COD_MAT);
--CRIANDO INDEX TIPO MAT
CREATE INDEX IX_MAT2 ON MATERIAL(COD_TIP_MAT);

	
--PRODUCAO
CREATE TABLE ORDEM_PROD
	(
    COD_EMPRESA INT NOT NULL,
	ID_ORDEM INT NOT NULL PRIMARY KEY,
	COD_MAT_PROD INT NOT NULL,
	QTD_PLAN DECIMAL(10,2) NOT NULL,
	QTD_PROD DECIMAL(10,2) NOT NULL,
	DATA_INI DATE,
	DATA_FIM DATE,
	SITUACAO CHAR(1) CONSTRAINT CK_OP1 CHECK (SITUACAO in ('A','P','F')),--A-ABERTA, P-PLANEJADA -F-FECHADA
    CONSTRAINT FK_OP1 FOREIGN KEY (COD_MAT_PROD,COD_EMPRESA) REFERENCES MATERIAL(COD_MAT,COD_EMPRESA)
    --CONSTRAINT FK_COD_EMP4 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
	);
    
--CRIANDO SEQUENCIA ORDEM DE PRODUCAO
 CREATE SEQUENCE SEQ_OP START WITH 1 INCREMENT BY 1 NOMAXVALUE;
    
--CRIACAO DE TABELAS APONTAMENTOS DE PRODUCAO
--DROP TABLE APONTAMENTOS
CREATE TABLE APONTAMENTOS
	(
    COD_EMPRESA INT NOT NULL,
	ID_APON INT NOT NULL PRIMARY KEY,
	ID_ORDEM INT NOT NULL,
	COD_MAT_PROD INT,
	QTD_APON DECIMAL(10,2),
	DATA_APON DATE NOT NULL,
	--CAMPO LOTE CRIADO NO FINAL
	--LOGIN, SERA CRIADO APOIS CRIACAO DA TABELA USUARIOS
    CONSTRAINT FK_AP1 FOREIGN KEY (COD_MAT_PROD,COD_EMPRESA) REFERENCES MATERIAL(COD_MAT,COD_EMPRESA),
	CONSTRAINT FK_APON1 FOREIGN KEY (ID_ORDEM) REFERENCES ORDEM_PROD(ID_ORDEM)
	);
    
-- CRIANDO SEQUENCIA PARA TABELA APONTAMENTOS
CREATE SEQUENCE SEQ_APON START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CRIACAO DA TABELA FICHA TECNICA
CREATE TABLE FICHA_TECNICA
(
    COD_EMPRESA INT NOT NULL,
	COD_MAT_PROD INT NOT NULL,
	COD_MAT_NECES INT NOT NULL,
	QTD_NECES DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_FIC1 FOREIGN KEY (COD_EMPRESA,COD_MAT_PROD) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT),
	CONSTRAINT FK_FIC2 FOREIGN KEY (COD_EMPRESA,COD_MAT_NECES) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
	);
    
-- CRIANDO SEQUENCIA PARA TABELA FICHA_TECNICA
CREATE SEQUENCE SEQ_FT START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CRIACAO DA TABELA CONSUMO
--DROP TABLE CONSUMO
CREATE TABLE CONSUMO
(
	ID_APON INT NOT NULL,
    COD_EMPRESA INT NOT NULL,
	COD_MAT_NECES INT NOT NULL,
	QTD_CONSUMIDA DECIMAL(10,2) NOT NULL,
	LOTE VARCHAR2(20) NOT NULL,
	CONSTRAINT FK_CONS1 FOREIGN KEY (COD_EMPRESA,COD_MAT_NECES) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT),
	CONSTRAINT FK_CONS2 FOREIGN KEY (ID_APON)  REFERENCES APONTAMENTOS(ID_APON)
	);


--SUPRIMENTOS
--CRIACAO DA TABELA 
CREATE TABLE ESTOQUE
	(
    COD_EMPRESA INT NOT NULL,
    COD_MAT INT NOT NULL,
	QTD_SALDO DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_EST1 FOREIGN KEY (COD_EMPRESA,COD_MAT) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT),
    CONSTRAINT PK_ESTOQUE1 PRIMARY KEY (COD_EMPRESA,COD_MAT)
	);
    
--DROP TABLE ESTOQUE_LOTE
--CRIACAO TABELAS ESTOQUE_LOTE
CREATE TABLE ESTOQUE_LOTE
	(
    COD_EMPRESA INT NOT NULL,
	COD_MAT INT NOT NULL,
	LOTE VARCHAR2(20) NOT NULL,
	QTD_LOTE DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_ESTL1 PRIMARY KEY (COD_EMPRESA,COD_MAT,LOTE), --PK COMPOSTA
	CONSTRAINT FK_ESTL1 FOREIGN KEY (COD_EMPRESA,COD_MAT) 
	REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
	);
--CRIACAO TABELA MOV ESTOQUE
--DROP TABLE ESTOQUE_MOV
	CREATE TABLE ESTOQUE_MOV
	(
	ID_MOV INT  NOT NULL PRIMARY KEY,
    COD_EMPRESA INT NOT NULL,
	TIP_MOV VARCHAR2(1),CONSTRAINT CK_MOV CHECK (TIP_MOV in ('S','E')), --S=SAIDA ,E=ENTRADA
	COD_MAT INT NOT NULL,
	LOTE  VARCHAR2(20) NOT NULL,
	QTD DECIMAL(10,2) NOT NULL,
	DATA_MOV DATE NOT NULL,
	DATA_HORA DATE NOT NULL,
	CONSTRAINT FK_ESTM1 FOREIGN KEY (COD_EMPRESA,COD_MAT) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
	--CAMPO LOGIN TABELA ESTOQUE_MOV CRIACAO APOS TABELA USUARIO
	);
    
    
-- CRIANDO SEQUENCIA PARA TABELA ESTOQUE_MOV
CREATE SEQUENCE SEQ_MOVEST START WITH 1 INCREMENT BY 1 NOMAXVALUE;
--CRIACAO TABELAS PED_COMPRAS
--DROP TABLE PED_COMPRAS	
CREATE TABLE PED_COMPRAS
	(
    COD_EMPRESA INT NOT NULL,
	NUM_PEDIDO INT  NOT NULL,
	ID_FOR INT NOT NULL,
	COD_PAGTO INT NOT NULL, --ALTERAR  COD_PAGTO TAB PED_COMPRAS PARA FOREIGN KEY APOS TABELA COND_PAGTO  	
	DATA_PEDIDO DATE NOT NULL,
	DATA_ENTREGA DATE NOT NULL,
	SITUACAO NCHAR(1) NOT NULL, --A-ABERTO P-PLANEJADO -F FINALIZADO
	TOTAL_PED DECIMAL(10,2),
	CONSTRAINT FK_PEDC1 FOREIGN KEY (ID_FOR) REFERENCES FORNECEDORES(ID_FOR),
    CONSTRAINT PK_PEDC1 PRIMARY KEY (COD_EMPRESA,NUM_PEDIDO)
	);
    
    -- CRIACAO DE TABELA DE PARAMETROS DE NUMEROS DE PEDIDO POR EMPRESA
    CREATE TABLE PARAM_PED_COMPRAS
    (
     COD_EMPRESA INT NOT NULL PRIMARY KEY,
     NUM_PED INT NOT NULL,
     CONSTRAINT FK_PPC FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
     );
     
--CRIACAO DA TABELA PEDIDO COMPRAS
CREATE TABLE PED_COMPRAS_ITENS
	(
    COD_EMPRESA INT NOT NULL,
	NUM_PEDIDO INT NOT NULL,
	SEQ_MAT INT NOT NULL,
	COD_MAT INT NOT NULL,
	QTD     INT NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_PEDIT1 FOREIGN KEY (COD_EMPRESA,NUM_PEDIDO) REFERENCES PED_COMPRAS(COD_EMPRESA,NUM_PEDIDO),
	CONSTRAINT FK_PEDIT2 FOREIGN KEY (COD_EMPRESA,COD_MAT) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT),
    CONSTRAINT PK_PED_C_IT PRIMARY KEY (COD_EMPRESA,NUM_PEDIDO,SEQ_MAT)
	);
	

--RH
--CRIACAO TABELAS CENTRO DE CUSTO
CREATE TABLE CENTRO_CUSTO
	(
    COD_EMPRESA INT NOT NULL,
	COD_CC VARCHAR2(4) NOT NULL,
	NOME_CC VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_CC1  FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT PK_CC1 PRIMARY KEY (COD_EMPRESA,COD_CC)
	);

--CRIACAO TABELAS CARGOS]
-- AVALIAR CENARIOS 
CREATE TABLE CARGOS 
	(COD_EMPRESA INT NOT NULL,
     COD_CARGO INT  NOT NULL,
	 NOME_CARGO VARCHAR2(50),
     CONSTRAINT FK_CARG1  FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
     CONSTRAINT PK_CARG1 PRIMARY KEY (COD_EMPRESA,COD_CARGO)
	 );
--CRIACAO TABELA FUNCIONARIO
CREATE TABLE FUNCIONARIO 
	(
    COD_EMPRESA INT NOT NULL,
	MATRICULA INT NOT NULL ,
	COD_CC VARCHAR2(4) NOT NULL,
	NOME   VARCHAR2(50) NOT NULL,
	RG     VARCHAR2(15) NOT NULL,
	CPF    VARCHAR2(15) NOT NULL,
	ENDERECO  VARCHAR2(50)NOT NULL,
	NUMERO VARCHAR2(10) NOT NULL,
	BAIRRO VARCHAR2(50) NOT NULL,
	COD_CIDADE VARCHAR2(7) NOT NULL,
	DATA_ADMISS DATE NOT NULL,
	DATE_DEMISS DATE,
	DATA_NASC DATE NOT NULL,
	TELEFONE VARCHAR2(15) NOT NULL,
	COD_CARGO INT NOT NULL,
	CONSTRAINT FK_FUNC1 FOREIGN KEY (COD_EMPRESA,COD_CC) REFERENCES CENTRO_CUSTO(COD_EMPRESA,COD_CC),
	CONSTRAINT FK_FUNC2 FOREIGN KEY (COD_CIDADE) REFERENCES CIDADES(COD_CIDADE),
	CONSTRAINT FK_FUNC3 FOREIGN KEY (COD_EMPRESA,COD_CARGO) REFERENCES CARGOS(COD_EMPRESA,COD_CARGO),
    CONSTRAINT PK_FUNC1 PRIMARY KEY(COD_EMPRESA,MATRICULA)
    );

-- TABELAS DE PARAMETROS DE MATRICULA POR EMPRESA
 CREATE TABLE PARAM_MATRICULA
  (
   COD_EMPRESA INT NOT NULL PRIMARY KEY,
   MATRICULA INT NOT NULL,
   CONSTRAINT FK_PMAT1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
   );

--CRIACAO TABELA SALARIO
CREATE TABLE SALARIO
	(
    COD_EMPRESA INT NOT NULL,
	MATRICULA INT NOT NULL,
	SALARIO DECIMAL(10,2)NOT NULL,
	CONSTRAINT FK_SAL1 FOREIGN KEY (COD_EMPRESA,MATRICULA) REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA),
    CONSTRAINT PK_SAL1 PRIMARY KEY (COD_EMPRESA,MATRICULA) 
    );
--CRIACAO TABLE FOLHA DE PAGTO
--DROP TABLE FOLHA_PAGTO
CREATE TABLE FOLHA_PAGTO
	(
    COD_EMPRESA INT NOT NULL,
	MATRICULA INT NOT NULL,
	TIPO_PGTO CHAR(1) NOT NULL,-- (M-FOLHA,A-ADTO,F-FERIAS,D-13º,R-RESC),
	TIPO CHAR(1)  NOT NULL,--P=PROVENTOS D-DESCONTO
	EVENTO VARCHAR2(30) NOT NULL, 
	MES_REF VARCHAR2(2)NOT NULL,
	ANO_REF VARCHAR2(4)NOT NULL,
	DATA_PAGTO DATE NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_FP1 FOREIGN KEY (COD_EMPRESA,MATRICULA) REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA)
	);
    
-- CRIANDO INDEX PARA OTIMARIZAR CONSULTAS
CREATE INDEX IX1_FPAG ON FOLHA_PAGTO(COD_EMPRESA,MES_REF,ANO_REF);



--SEGURANCA
--CRIACAO TA TABELAS USARIOS 
CREATE TABLE USUARIOS
	(
    COD_EMPRESA INT NOT NULL,
	LOGIN VARCHAR2(30) NOT NULL ,
	MATRICULA INT NOT NULL,
	SENHA   VARCHAR2(32) NOT NULL,
	SITUACAO CHAR(1) NOT NULL, --A=ATIVO -B BLOQUEADO
	CONSTRAINT FK_US1 FOREIGN KEY (COD_EMPRESA,MATRICULA) 
	REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA),
    CONSTRAINT PK_USER PRIMARY KEY(COD_EMPRESA,MATRICULA)
	);
    
-- CRIANDO INDEX UNIQUE PARA LOGIN
CREATE UNIQUE INDEX IX1_USER ON USUARIOS (LOGIN);


--FINANCEIRO
--CRIACAO TABELA CONTAS A RECEBER
CREATE TABLE CONTAS_RECEBER
	(
    COD_EMPRESA INT NOT NULL,
	ID_DOC INT  NOT NULL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
	ID_DOC_ORIG INT NOT NULL, --ALTER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
	PARC INT NOT NULL,
	DATA_VENC DATE NOT NULL,
	DATA_PAGTO DATE,
	VALOR DECIMAL(10,2),
	CONSTRAINT FK_CR1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_CR2 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
	);
    
-- CRIANDO SEQUENCIA PARA TABELA CONTAS_RECEBER
CREATE SEQUENCE SEQ_CRE START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CRIACAO TABELA CONTAS A PAGAR
--DROP TABLE CONTAS_PAGAR
CREATE TABLE CONTAS_PAGAR
	(
    COD_EMPRESA INT NOT NULL,
	ID_DOC INT  NOT NULL PRIMARY KEY,
    ID_FOR INT NOT NULL,
	ID_DOC_ORIG INT NOT NULL, --ALTER CAMPO ID_DOC_ORIG PARA FK TABELA NOTA_FISCAL
	PARC INT NOT NULL,
	DATA_VENC DATE NOT NULL,
	DATA_PAGTO DATE ,
	VALOR DECIMAL(10,2),
	CONSTRAINT FK_CP1 FOREIGN KEY (ID_FOR) REFERENCES FORNECEDORES(ID_FOR),
    CONSTRAINT FK_CP2 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
	);
    
-- CRIANDO SEQUENCIA PARA TABELA CONTAS_PAGAR
CREATE SEQUENCE SEQ_CAP START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CRIACAO TABELA CONDIÇÕES DE PAGTO
CREATE TABLE COND_PAGTO
	(
	COD_PAGTO INT  NOT NULL PRIMARY KEY,
	NOME_CP VARCHAR2(50) NOT NULL 
	);
    
-- CRIANDO SEQUENCIA PARA TABELA COND_PAGTO
CREATE SEQUENCE SEQ_PAGTO START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CRIACAO DA TABELAS DETALHES DE CONDICAO DE PAGTO COM PARCELA
CREATE TABLE COND_PAGTO_DET
	(
	COD_PAGTO INT NOT NULL,
	PARC     INT NOT NULL,
	DIAS     INT NOT NULL,
	PCT  DECIMAL(10,2)NOT NULL,--PERCENTUAL DA PARCELA
	CONSTRAINT FK_CONDP1 FOREIGN KEY (COD_PAGTO) 
	REFERENCES COND_PAGTO(COD_PAGTO)
	);

--COMERCIAL
--CRIACAO TABELA PEDIDO DE VENDAS
CREATE TABLE PED_VENDAS
	(
    COD_EMPRESA INT NOT NULL,
	NUM_PEDIDO INT  NOT NULL,
	ID_CLIENTE INT NOT NULL,
	COD_PAGTO INT NOT NULL, 
	DATA_PEDIDO DATE NOT NULL,
	DATA_ENTREGA DATE NOT NULL,
	SITUACAO NCHAR(1) NOT NULL, --A-ABERTO P-PLANEJADO -F FINALIZADO
	TOTAL_PED DECIMAL(10,2),
	CONSTRAINT FK_PV1 FOREIGN KEY (ID_CLIENTE)REFERENCES CLIENTES(ID_CLIENTE),
	CONSTRAINT FK_PV2 FOREIGN KEY (COD_PAGTO) REFERENCES COND_PAGTO(COD_PAGTO),
    CONSTRAINT FK_PV3 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA),
    CONSTRAINT PK_PV1 PRIMARY KEY(COD_EMPRESA,NUM_PEDIDO)
	);
    
   -- CRIACAO DE TABELA DE PARAMETROS DE NUMEROS DE PEDIDO DE VENDAS POR EMPRESA
    CREATE TABLE PARAM_PED_VENDAS
    (
     COD_EMPRESA INT NOT NULL PRIMARY KEY,
     NUM_PED INT NOT NULL,
     CONSTRAINT FK_PV FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
     );
    
--CRIACAO DA TABELA PEDIDO VENDAS ITENS
--DROP TABLE PED_VENDAS_ITENS
CREATE TABLE PED_VENDAS_ITENS
	(
    COD_EMPRESA INT NOT NULL,
	NUM_PEDIDO INT NOT NULL,
	SEQ_MAT INT NOT NULL,
	COD_MAT INT NOT NULL,
	QTD     INT NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_PVIT1 FOREIGN KEY (COD_EMPRESA,NUM_PEDIDO) REFERENCES PED_VENDAS(COD_EMPRESA,NUM_PEDIDO),
    CONSTRAINT FK_PVIT2 FOREIGN KEY (COD_EMPRESA,COD_MAT) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
	);

--CRIACAO TABELAS VENDEDORES
--DROP TABLE VENDEDORES
CREATE TABLE VENDEDORES
    (
     COD_EMPRESA INT NOT NULL,
     ID_VEND INT NOT NULL,
	 MATRICULA INT NOT NULL,
 	 CONSTRAINT FK_VEND1 FOREIGN KEY (COD_EMPRESA,MATRICULA) REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA),
     CONSTRAINT PK_VEND1 PRIMARY KEY (COD_EMPRESA,MATRICULA)
	 );
    
-- CRIANDO SEQUENCIA PARA COD DO VENDEDOR
CREATE SEQUENCE SEQ_VENDEDORES START WITH 1 INCREMENT BY 1 NOMAXVALUE;
    
--CRIACAO DE TAB GERENTES DE VENDAS
CREATE TABLE GERENTES
    ( COD_EMPRESA INT NOT NULL,
      ID_GER INT  NOT NULL,
	  MATRICULA INT NOT NULL,
 	CONSTRAINT FK_GER1 FOREIGN KEY (COD_EMPRESA,MATRICULA) REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA),
    CONSTRAINT PK_GER1 PRIMARY KEY (COD_EMPRESA,MATRICULA)
	 );
     
    
-- CRIANDO SEQUENCIA PARA COD DO VENDEDOR
CREATE SEQUENCE SEQ_GERENTES START WITH 1 INCREMENT BY 1 NOMAXVALUE;

--CANAL DE VENDAS RELACIONA GERENTE COM VENDEDOR
CREATE TABLE CANAL_VENDAS_G_V
	(
    COD_EMPRESA INT NOT NULL,
	ID_GER INT NOT NULL,
	ID_VEND INT NOT NULL,
    CONSTRAINT FK_CGV3 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
	);
    

--CANAL DE VENDAS RELACIONA VENDEDOR COM CLIENTE
--DROP TABLE CANAL_VENDAS_V_C
CREATE TABLE CANAL_VENDAS_V_C
	(
    COD_EMPRESA INT NOT NULL,
	ID_VEND INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CONSTRAINT FK_CVC2 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_CCV1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA) 
	);
--CRIACAO DE TABELA PARA REGISTRA META DE VENDAS MES A MES/ANO
CREATE TABLE META_VENDAS
	(
    COD_EMPRESA INT NOT NULL,
	ID_VEND INT NOT NULL,
	ANO VARCHAR2(4) NOT NULL,
	MES VARCHAR2(2) NOT NULL,
	VALOR DECIMAL(10,2),
	CONSTRAINT FK_MV1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
	);


--FISCAL
--CRIACAO DA TABELA DOS CODIGO DE OPERACOES FISCAIS
--DROP TABLE CFOP
	CREATE TABLE CFOP
	(
	COD_CFOP VARCHAR2(5) NOT NULL PRIMARY KEY,
	DESC_CFOP VARCHAR2(255) NOT NULL
	);
--CRIACAO DA TABELA NOTA_FISCAL
--DROP TABLE NOTA_FISCAL
--DROP TABLE NOTA_FISCAL_ITENS
CREATE TABLE NOTA_FISCAL
	(
    COD_EMPRESA INT NOT NULL,
	NUM_NF INT NOT NULL,
	TIP_NF CHAR(1) NOT NULL, --E ENTRADA, S- SAIDA
	COD_CFOP VARCHAR2(5) NOT NULL,
	ID_CLIFOR INT NOT NULL,
	COD_PAGTO INT NOT NULL, 
	DATA_EMISSAO DATE NOT NULL,
	DATA_ENTREGA DATE NOT NULL,
	TOTAL_NF DECIMAL(10,2),
	INTEGRADA_FIN CHAR(1) DEFAULT('N'),
	INTEGRADA_SUP CHAR(1) DEFAULT('N'),
	CONSTRAINT FK_NF1 FOREIGN KEY (COD_CFOP) REFERENCES CFOP(COD_CFOP),
	CONSTRAINT FK_NF2 FOREIGN KEY (COD_PAGTO) REFERENCES COND_PAGTO(COD_PAGTO),
    CONSTRAINT PK_NF1 PRIMARY KEY (COD_EMPRESA,NUM_NF)
	);
--CRIACAO DA TABELA NOTA_FISCAL_ITENS
CREATE TABLE NOTA_FISCAL_ITENS
	(
    COD_EMPRESA INT NOT NULL,
	NUM_NF INT NOT NULL,
	SEQ_MAT INT NOT NULL,
	COD_MAT INT NOT NULL,
	QTD     INT NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	PED_ORIG  INT NOT NULL,
	CONSTRAINT FK_NFIT1 FOREIGN KEY (COD_EMPRESA,NUM_NF) REFERENCES NOTA_FISCAL(COD_EMPRESA,NUM_NF),
	CONSTRAINT FK_NFIT2 FOREIGN KEY (COD_EMPRESA,COD_MAT) REFERENCES MATERIAL(COD_EMPRESA,COD_MAT)
	);
    
    --CRIACAO TABELAS PARAMETRO NUMERACAO NFE

    CREATE TABLE PARAM_NFE
    (
     COD_EMPRESA INT NOT NULL PRIMARY KEY,
     NUM_NFE INT NOT NULL,
     CONSTRAINT FK_NFE1 FOREIGN KEY (COD_EMPRESA) REFERENCES EMPRESA(COD_EMPRESA)
     );
    


--CRIACAO TABELAS PARAMETRO DE INSS

CREATE TABLE PARAM_INSS
(
 VIGENCIA_INI DATE,
 VIGENCIA_FIM DATE,
 VALOR_DE DECIMAL(10,2) NOT NULL,
 VALOR_ATE DECIMAL(10,2) NOT NULL,
 PCT DECIMAL(10,2) NOT NULL
 );

--CRIACAO DE TABELAS DE PARAMETRO DO IRRF
CREATE TABLE PARAM_IRRF
(
 VIGENCIA_INI DATE,
 VIGENCIA_FIM DATE,
 VALOR_DE DECIMAL(10,2) NOT NULL,
 VALOR_ATE DECIMAL(10,2) NOT NULL,
 PCT DECIMAL(10,2) NOT NULL,
 VAL_ISENT DECIMAL(10,2)
 );


 --CRIACAO TABELAS AUDIT SALARIO
 CREATE TABLE AUDITORIA_SALARIO
 (  
    COD_EMPRESA INT NOT NULL,
	MATRICULA INT NOT NULL,
	SAL_ANTES DECIMAL(10, 2) NOT NULL,
	SAL_DEPOIS DECIMAL(10, 2) NOT NULL,
	USUARIO VARCHAR2(20) NOT NULL,
	DATA_ATUALIZACAO DATE NOT NULL,
    CONSTRAINT FK_AUDIT1 FOREIGN KEY (COD_EMPRESA,MATRICULA) REFERENCES FUNCIONARIO(COD_EMPRESA,MATRICULA)
);

--ADD CAMPO LOGIN TABELA APONTAMENTOS CRIACAO APOS TABELA USUARIOS E FK
  ALTER TABLE APONTAMENTOS ADD LOGIN VARCHAR2(30)NOT NULL;
 
  ALTER TABLE APONTAMENTOS ADD LOTE VARCHAR2(20) NOT NULL;
  --REMOVENDO CONSTRAINT PARA TESTE
  ALTER TABLE CONSUMO DROP CONSTRAINT  FK_CONS2;
  --ALTER TABLE APONTAMENTOS DROP CONSTRAINT  FK_APONT3

--ADD CAMPO LOGIN TABELA ESTOQUE_MOV  CRIACAO APOS TABELA USUARIO
  ALTER TABLE ESTOQUE_MOV ADD LOGIN VARCHAR2(30)NOT NULL;
  
 

--ALTERAR  COD_PAGTO TAB PED_COMPRAS PARA FOREIGN KEY APOS TABELA COND_PAGTO
  ALTER TABLE PED_COMPRAS ADD 
  FOREIGN KEY (COD_PAGTO) REFERENCES COND_PAGTO(COD_PAGTO);

  
 